version: "3"
services:
  db:
    image: postgres
    container_name: prapp-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: prapp
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
  # redis:
  #   image: redis
  #   container_name: prapp-redis
  #   ports:
  #     - 6379:6379
  #   restart: always
